/**
 * NIP-44 v2 against the official vectors.
 *
 * `fixtures/nip44-v2.json` is a **verbatim** copy of
 * https://github.com/paulmillr/nip44/blob/main/nip44.vectors.json — no wrapper,
 * no reformatting, no added description field, so `curl | diff` is a one-line
 * check that this repository has not quietly forked the ciphersuite. Every
 * other fixture in this package is generated by us and committed so other
 * languages can read it; this one is the opposite and the reason is the same.
 * Cryptography is where "our implementation agrees with itself" is worth least.
 *
 * The invalid cases carry as much weight as the valid ones. An encrypt/decrypt
 * round trip passes against an implementation that ignores the MAC entirely.
 */

import assert from 'node:assert/strict'
import { describe, test } from 'node:test'
import { readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { bytesToHex, hexToBytes, utf8ToBytes } from '@noble/hashes/utils.js'
import { schnorr } from '@noble/curves/secp256k1.js'
import { sha256 } from '@noble/hashes/sha2.js'
import {
  calcPaddedLen,
  conversationKey,
  messageKeys,
  nip44Decrypt,
  nip44Encrypt,
} from '../src/nip44.ts'

interface Vectors {
  v2: {
    valid: {
      get_conversation_key: { sec1: string; pub2: string; conversation_key: string }[]
      get_message_keys: {
        conversation_key: string
        keys: { nonce: string; chacha_key: string; chacha_nonce: string; hmac_key: string }[]
      }
      calc_padded_len: [number, number][]
      encrypt_decrypt: {
        sec1: string
        sec2: string
        conversation_key: string
        nonce: string
        plaintext: string
        payload: string
      }[]
      encrypt_decrypt_long_msg: {
        conversation_key: string
        nonce: string
        pattern: string
        repeat: number
        plaintext_sha256: string
        payload_sha256: string
      }[]
    }
    invalid: {
      encrypt_msg_lengths: number[]
      get_conversation_key: { sec1: string; pub2: string; note: string }[]
      decrypt: {
        conversation_key: string
        nonce: string
        plaintext: string
        payload: string
        note: string
      }[]
    }
  }
}

const vectors: Vectors = JSON.parse(
  readFileSync(fileURLToPath(new URL('../fixtures/nip44-v2.json', import.meta.url)), 'utf8'),
)
const v2 = vectors.v2

function pubkeyOf(sec: string): string {
  // Deriving pub2 from sec2 rather than reading it: the vectors give both keys
  // as secrets for the round-trip cases, and the x-only conversion is exactly
  // the step an implementation can get wrong in a way that still round-trips
  // against itself.
  return bytesToHex(schnorr.getPublicKey(hexToBytes(sec)))
}

describe('nip44 conversation keys', () => {
  test('matches all 35 official vectors', () => {
    assert.ok(v2.valid.get_conversation_key.length > 30)
    for (const v of v2.valid.get_conversation_key) {
      assert.equal(bytesToHex(conversationKey(v.sec1, v.pub2)), v.conversation_key)
    }
  })

  test('is symmetric in the pair, which is what makes it usable without a handshake', () => {
    const [a] = v2.valid.encrypt_decrypt
    assert.ok(a)
    const ab = conversationKey(a!.sec1, pubkeyOf(a!.sec2))
    const ba = conversationKey(a!.sec2, pubkeyOf(a!.sec1))
    assert.equal(bytesToHex(ab), bytesToHex(ba))
    assert.equal(bytesToHex(ab), a!.conversation_key)
  })

  test('refuses every invalid key pair', () => {
    assert.ok(v2.invalid.get_conversation_key.length > 0)
    for (const v of v2.invalid.get_conversation_key) {
      assert.throws(() => conversationKey(v.sec1, v.pub2), v.note)
    }
  })
})

describe('nip44 message keys', () => {
  test('matches all 32 official vectors', () => {
    const key = hexToBytes(v2.valid.get_message_keys.conversation_key)
    for (const v of v2.valid.get_message_keys.keys) {
      const keys = messageKeys(key, hexToBytes(v.nonce))
      assert.equal(bytesToHex(keys.chachaKey), v.chacha_key)
      assert.equal(bytesToHex(keys.chachaNonce), v.chacha_nonce)
      assert.equal(bytesToHex(keys.hmacKey), v.hmac_key)
    }
  })
})

describe('nip44 padding', () => {
  test('matches all official calc_padded_len vectors', () => {
    for (const [input, expected] of v2.valid.calc_padded_len) {
      assert.equal(calcPaddedLen(input), expected, `${input}`)
    }
  })
})

describe('nip44 encrypt and decrypt', () => {
  test('reproduces every official payload byte for byte', () => {
    for (const v of v2.valid.encrypt_decrypt) {
      const key = conversationKey(v.sec1, pubkeyOf(v.sec2))
      assert.equal(bytesToHex(key), v.conversation_key)
      assert.equal(nip44Encrypt(v.plaintext, key, hexToBytes(v.nonce)), v.payload)
      assert.equal(nip44Decrypt(v.payload, key), v.plaintext)
    }
  })

  test('handles the long-message vectors, up to the 65535-byte ceiling', () => {
    for (const v of v2.valid.encrypt_decrypt_long_msg) {
      const plaintext = v.pattern.repeat(v.repeat)
      assert.equal(bytesToHex(sha256(utf8ToBytes(plaintext))), v.plaintext_sha256)
      const payload = nip44Encrypt(plaintext, hexToBytes(v.conversation_key), hexToBytes(v.nonce))
      assert.equal(bytesToHex(sha256(utf8ToBytes(payload))), v.payload_sha256)
      assert.equal(nip44Decrypt(payload, hexToBytes(v.conversation_key)), plaintext)
    }
  })

  test('refuses every invalid payload', () => {
    assert.ok(v2.invalid.decrypt.length > 10)
    for (const v of v2.invalid.decrypt) {
      assert.throws(() => nip44Decrypt(v.payload, hexToBytes(v.conversation_key)), v.note)
    }
  })

  test('refuses plaintext lengths outside 1..65535', () => {
    const key = hexToBytes(v2.valid.get_message_keys.conversation_key)
    for (const length of v2.invalid.encrypt_msg_lengths) {
      assert.throws(() => nip44Encrypt('x'.repeat(length), key), `${length}`)
    }
  })

  test('a tampered ciphertext fails the MAC rather than decrypting to noise', () => {
    const key = hexToBytes(v2.valid.get_message_keys.conversation_key)
    const payload = nip44Encrypt('deploy api 1.4.2 to production', key)
    // Flip one base64 character in the middle, which lands in the ciphertext.
    const at = Math.floor(payload.length / 2)
    const flipped = `${payload.slice(0, at)}${payload[at] === 'A' ? 'B' : 'A'}${payload.slice(at + 1)}`
    assert.throws(() => nip44Decrypt(flipped, key), /MAC|padding|base64|invalid/i)
  })

  test('the wrong key fails the MAC, so a stale epoch never half-decrypts', () => {
    const key = hexToBytes(v2.valid.get_message_keys.conversation_key)
    const other = hexToBytes(v2.valid.get_conversation_key[0]!.conversation_key)
    const payload = nip44Encrypt('the channel secret rotated', key)
    assert.throws(() => nip44Decrypt(payload, other), /MAC/)
  })
})
