package contextpack

import (
	"encoding/json"
	"math/rand"
	"os"
	"strings"
	"testing"

	"github.com/nbd-wtf/go-nostr"
)

// fixturePath is the golden case both packers are held to. Generated by
// `pnpm --filter @quorum/sdk fixtures` from the TypeScript implementation, so
// this file is the Go half of a conformance claim rather than a test of Go
// against itself: if the two ever disagree, an agent's view of a thread changes
// depending on whether its channel is encrypted.
const fixturePath = "../../../../packages/sdk/fixtures/context-pack.json"

type fixture struct {
	Algorithm string         `json:"algorithm"`
	Thread    string         `json:"thread"`
	Requester string         `json:"requester"`
	Events    []*nostr.Event `json:"events"`
	Cases     []struct {
		Name     string          `json:"name"`
		Why      string          `json:"why"`
		Request  json.RawMessage `json:"request"`
		Expected string          `json:"expected"`
	} `json:"cases"`
}

func load(t *testing.T) fixture {
	t.Helper()
	raw, err := os.ReadFile(fixturePath)
	if err != nil {
		t.Fatalf("reading the golden fixture: %v\n\nRun `pnpm --filter @quorum/sdk fixtures` to write it.", err)
	}
	var f fixture
	if err := json.Unmarshal(raw, &f); err != nil {
		t.Fatalf("parsing the golden fixture: %v", err)
	}
	if len(f.Cases) == 0 {
		t.Fatal("the golden fixture has no cases")
	}
	return f
}

func firstRequest(t *testing.T, f fixture) Request {
	t.Helper()
	var request Request
	if err := json.Unmarshal(f.Cases[0].Request, &request); err != nil {
		t.Fatalf("parsing the request: %v", err)
	}
	return request
}

// TestMatchesTheTypeScriptPacker is the whole point of this package existing
// twice. Byte equality, not field equality: the result is the content of a
// signed event, so two packers that agree on the values and differ on the bytes
// produce different event ids and have not agreed on anything.
func TestMatchesTheTypeScriptPacker(t *testing.T) {
	f := load(t)
	if f.Algorithm != Algorithm {
		t.Fatalf("the fixture was generated for %q, this packer implements %q", f.Algorithm, Algorithm)
	}

	for _, c := range f.Cases {
		t.Run(c.Name, func(t *testing.T) {
			var request Request
			if err := json.Unmarshal(c.Request, &request); err != nil {
				t.Fatalf("parsing the request: %v", err)
			}

			got := Pack(request, f.Requester, f.Events).CanonicalJSON()
			if got != c.Expected {
				t.Errorf("%s\n\nfirst divergence at byte %d\n\n  got  %s\n  want %s",
					c.Why, divergence(got, c.Expected), around(got), around(c.Expected))
			}
		})
	}
}

// TestOrderOfTheInputDoesNotMatter guards the property the byte-equality claim
// rests on but a golden fixture cannot check: the two packers are fed by
// different code — a relay store query here, a client backfill there — and
// nothing makes those arrive in the same order. A pack that depended on arrival
// order would pass the fixture and still diverge in production.
func TestOrderOfTheInputDoesNotMatter(t *testing.T) {
	f := load(t)
	request := firstRequest(t, f)
	want := Pack(request, f.Requester, f.Events).CanonicalJSON()

	for seed := int64(0); seed < 8; seed++ {
		shuffled := make([]*nostr.Event, len(f.Events))
		copy(shuffled, f.Events)
		rng := rand.New(rand.NewSource(seed))
		rng.Shuffle(len(shuffled), func(i, j int) { shuffled[i], shuffled[j] = shuffled[j], shuffled[i] })

		if got := Pack(request, f.Requester, shuffled).CanonicalJSON(); got != want {
			t.Fatalf("shuffle %d produced different bytes at %d", seed, divergence(got, want))
		}
	}
}

// TestNothingButTheThread is stated separately from the fixture because it is
// the failure that looks like success: a segment from another thread reads as
// ordinary history, and the only reader who would notice is the model being
// asked to act on it.
func TestNothingButTheThread(t *testing.T) {
	f := load(t)
	result := Pack(firstRequest(t, f), f.Requester, f.Events)

	inThread := make(map[string]bool)
	for _, event := range f.Events {
		if belongsTo(event, f.Thread) {
			inThread[event.ID] = true
		}
	}
	if len(result.Segments) == 0 {
		t.Fatal("the first case packs nothing; it cannot check thread selection")
	}
	for _, segment := range result.Segments {
		if !inThread[segment.EventID] {
			t.Errorf("segment %s does not belong to the thread", segment.EventID[:8])
		}
	}
}

func TestTokens(t *testing.T) {
	// The framing overhead is charged even to an empty segment, because the
	// header a caller renders costs the same whatever the body says.
	for _, c := range []struct {
		text string
		want int
	}{
		{"", SegmentOverheadTokens},
		{"xxxx", SegmentOverheadTokens + 1},
		{"xxxxx", SegmentOverheadTokens + 2},
		// Two bytes in UTF-8, one code point: the proxy counts bytes, so the
		// same sentence costs more in Greek than in English. Documented rather
		// than fixed — a real tokenizer would make the two packers depend on a
		// vendor's vocabulary file shipping identically in both languages.
		{"é", SegmentOverheadTokens + 1},
	} {
		if got := Tokens(c.text); got != c.want {
			t.Errorf("Tokens(%q) = %d, want %d", c.text, got, c.want)
		}
	}
}

func TestTruncateCountsCodePoints(t *testing.T) {
	long := strings.Repeat("\U0001F600", 500)
	got := truncate(long)

	// 400 code points plus the ellipsis. A UTF-16 implementation would keep 200
	// emoji, and a byte-counting one would end in the middle of a character.
	if runes := []rune(got); len(runes) != MaxSegmentChars+1 {
		t.Fatalf("truncated to %d code points, want %d", len(runes), MaxSegmentChars+1)
	}
	if !strings.HasSuffix(got, "…") {
		t.Error("a cut segment must say so")
	}
	if truncate("short") != "short" {
		t.Error("a segment under the limit must come back untouched")
	}
}

// TestCanonicalJSONEscapes pins the characters that make `encoding/json`
// unusable here: it would write \u003c, \u003e and \u0026 for
// the three HTML ones and \u2028 for the line separator, where JavaScript
// writes all four through. A C0 control has to come out as lowercase
// \u0007 on both sides.
func TestCanonicalJSONEscapes(t *testing.T) {
	text := "a < b & c > d \u2028 \"q\" \\ \u0007 \t"
	result := Result{
		Thread:    "t",
		Algorithm: Algorithm,
		Segments: []Segment{{
			EventID:    "e",
			Text:       text,
			Provenance: Provenance{Pubkey: "p", Kind: "human", Trust: "member"},
		}},
	}

	want := `"a < b & c > d ` + "\u2028" + ` \"q\" \\ \u0007 \t"`
	if got := result.CanonicalJSON(); !strings.Contains(got, want) {
		t.Errorf("got  %s\nwant it to contain %s", got, want)
	}

	// And the bytes have to survive a round trip, or the writer is producing
	// something only it can read.
	var decoded Result
	if err := json.Unmarshal([]byte(result.CanonicalJSON()), &decoded); err != nil {
		t.Fatalf("the writer produced invalid JSON: %v", err)
	}
	if decoded.Segments[0].Text != text {
		t.Error("the text did not survive a round trip")
	}
}

// TestCanonicalKeysAreSorted re-derives RFC 8785's key order from the emitted
// bytes rather than trusting that the literals in canonical.go were typed in
// the right order. The writer hard-codes the order; this is what stops a new
// field being appended where it reads well instead of where it belongs.
func TestCanonicalKeysAreSorted(t *testing.T) {
	f := load(t)
	raw := Pack(firstRequest(t, f), f.Requester, f.Events).CanonicalJSON()

	decoder := json.NewDecoder(strings.NewReader(raw))
	checkKeyOrder(t, decoder)
}

// checkKeyOrder walks one JSON value, asserting that every object's keys appear
// in ascending order. json.Decoder yields tokens in document order, which is
// the only way to see the order a writer chose.
func checkKeyOrder(t *testing.T, decoder *json.Decoder) {
	t.Helper()
	token, err := decoder.Token()
	if err != nil {
		t.Fatalf("reading the emitted JSON: %v", err)
	}
	delim, isDelim := token.(json.Delim)
	if !isDelim {
		return
	}

	switch delim {
	case '{':
		previous := ""
		for decoder.More() {
			key, err := decoder.Token()
			if err != nil {
				t.Fatalf("reading a key: %v", err)
			}
			name, _ := key.(string)
			if previous != "" && name <= previous {
				t.Errorf("key %q comes after %q, which is not RFC 8785 order", name, previous)
			}
			previous = name
			checkKeyOrder(t, decoder)
		}
	case '[':
		for decoder.More() {
			checkKeyOrder(t, decoder)
		}
	}
	if _, err := decoder.Token(); err != nil {
		t.Fatalf("reading a closing delimiter: %v", err)
	}
}

func divergence(a, b string) int {
	for i := 0; i < len(a) && i < len(b); i++ {
		if a[i] != b[i] {
			return i
		}
	}
	return min(len(a), len(b))
}

// around trims a long result to the region a reader needs, so a one-byte
// difference in a 20kB pack does not arrive as 40kB of test output.
func around(s string) string {
	const window = 200
	if len(s) <= window*2 {
		return s
	}
	return s[:window] + " … " + s[len(s)-window:]
}
